### ISSUE TITLE
Resizing Surge XT on a 4k monitor (4096x2160) forgets settings, drop down menus still small when you zoom.

### ISSUE THREAD

**Issue by tsigoulas** [surge-synthesizer/releases-xt#1]
Resizing Surge XT on a 4k monitor (4096x2160) doesn't hold-remember settings. Also, the drop down menus are small even when you resize. I'm on Windows 10 64bit,  custom scaling at 200%, Reaper 6-64 bit (latest Version), Surge XT (Latest nightly version OCT-29th 2021). The SurgeXTUserDefaults.xml file in "my documents" folder is updating the user settings but the plugin itself forgets to reload the zoom settings. I hope that helps, thanks!
[https://i.imgur.com/ksXgqlG.gif](url)

**Comment by baconpaul** [comment]
Dup of https://github.com/surge-synthesizer/surge/issues/5282
