### ISSUE TITLE
Virtual keyboard: octave shift with note off

### ISSUE THREAD

**Issue by j5v** [surge-synthesizer/releases-xt#5]
Note-off is sent for the wrong MIDI note when octave shift has been used since note-on.
Likely a bug in JUCE rather than Surge.

Steps:
- Enable the virtual keyboard in an open Surge window.
- Press and hold a key (say "F")
- Press C to shift octave
- Release the note key ("F")
The note remains on.

Expected result:
The note ends.

**Comment by baconpaul** [comment]
Oh hi @j5v you opened both of these in the release repo. I should disable issues here. But one of us should move em to the surge repo in the next day or two :)
