### ISSUE TITLE
ADSR Graph

### ISSUE THREAD

**Issue by MadCoding208** [surge-synthesizer/releases-xt#6]
The Digital type of ADSR graph is showing a weird image while the Analog version is showing the perfect image.
![Untitled](https://user-images.githubusercontent.com/43301199/147718974-5b0af8bd-cfc6-4c66-bddc-38e1ca1d0788.jpg)

PC Specification
os:-Windows 7 32bit
daw:-FL Studio Trial Edition

**Comment by mkruselj** [comment]
You're not using the latest Surge XT nightly. This was fixed over a week ago.

Also, this is the wrong repository to add issues to! Use https://github.com/surge-synthesizer/surge/issues

Thanks!
